# # logger
LOGGER_LEVEL: 'debug'
JWT_SECRET: 'admin!@#123'
JWT_EXPIRE: '86400' # 单位秒
REFRESH_TOKEN_SECRET: 'admin!@#123'
REFRESH_TOKEN_EXPIRE: '2592000'
# swagger
# 数据库配置
swagger:
  ENABLE: true
  PATH: 'api-docs'
  VERSION: '1.0'

db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: '123456'
    database: 'kapok'
    port: 3306
    charser: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true
redis:
  PORT: 6379
  HOST: 127.0.0.1
  PASSWORD: 123456
  DB: 0
smtp:
  HOST: 'smtp.163.com'
  PORT: '465'
  USER: 'nest_admin@163.com'
  PASS: 'VIPLLOTPMETXTROYU'
